name: store
description: A new Flutter project.

publish_to: 'none' 


version: 1.0.0+1

environment:
  sdk: '>=2.18.2 <3.0.0'


dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  get: ^4.6.6 
  google_fonts: ^6.1.0
  flutter_svg: ^1.1.5
  dropdown_textfield: ^1.0.5
  country_state_city_pro: ^0.0.5
  google_sign_in: ^5.0.0
  firebase_core: ^2.2.0
  firebase_auth: ^4.1.4
  cloud_firestore: ^4.0.5
  sqflite: ^2.2.2
  path: ^1.8.2
  flrx_validator: ^0.6.0
  shimmer: ^3.0.0
  carousel_slider: ^4.2.1

 

dev_dependencies:
  flutter_test:
    sdk: flutter


  flutter_launcher_icons: ^0.11.0

  flutter_lints: ^2.0.0

flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "aseets/image/logo.png"

flutter:

  uses-material-design: true
  assets:
    - aseets/image/
